const DAYS = ['Mon', 'Tue', 'Wed', 'Thur', 'Fri', 'Sat', 'Sun']
const SPLITS =
{
    'ppl': ['Push', 'Pull', 'Legs', 'Push', 'Pull', 'Legs', 'Rest'],
    'upper-lower': ['Upper', 'Lower', 'Rest', 'Upper', 'Lower', 'Rest', 'Rest'],
    'full-body': ['Full Body', 'Rest', 'Full Body', 'Rest', 'Full Body', 'Rest',  'Rest']
}

export default function renderSchedule(splitType, startDay, customDays = null){
    const schedule = (splitType === 'custom') ? customDays : SPLITS[splitType]
    //Rotate Schedule logic
    // Column one is day: column i (Mon=0, Tue=1 ... Sun=6)
    // Days are 7
    // Formula to rotate schedule based on startday: schedule[(i-startday + 7) % 7]

    const labels = DAYS.map((_, i) => 
        (splitType === 'custom') ? schedule[i] : schedule[(i-startDay + 7) % 7]
    )
    const cells = labels.map((label, i) => { 
        //const label = (splitType === 'custom') ? schedule[i] : schedule[(i-startDay + 7) % 7]
        const isRest = (label === 'Rest')
        return(
            `
            <div class="split-cell ${isRest ? 'split-rest' : 'split-workout'}">
                <div class="split-day">${DAYS[i]}</div>
                <div class="split-label">${label}</div>
            </div>
            `
        )
    })
    document.getElementById('split-result').innerHTML = 
    `<div class="split-grid">${cells.join("")}</div>`
    return labels
}

export function generateICS(labels, startDate = new Date()){
    const lines = [
        'BEGIN:VCALENDAR',
        'VERSION:2.0',
        'PRODID:-//Phalanx//WorkoutSplit//EN',
        'CALSCALE:GREGORIAN',
        'METHOD:PUBLISH'
    ]
    const nowStr = new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z'

    //Generate for 4 weeks 
    for (let week = 0; week < 4; week++){
        labels.forEach((label, i) => {
            const eventDate = new Date(startDate)
            eventDate.setDate(startDate.getDate() + (week * 7) + i)

            //helper to pad numbers (e.g., 5 -> "05")
            const pad = n => String(n).padStart(2, '0')

            //Format YYYYMMDD
            const start = `${eventDate.getFullYear()}${pad(eventDate.getMonth() + 1)}${pad(eventDate.getDate())}`

            //DTEND is the day AFTER for all-day events
            const endElem = new Date(eventDate);
            endElem.setDate(eventDate.getDate() + 1)
            const end = `${endElem.getFullYear()}${pad(endElem.getMonth() + 1)}${pad(endElem.getDate())}`

            const uid = `${nowStr}-${week}-${i}@phalanx.app`

            lines.push(
                'BEGIN:VEVENT',
                `UID:${uid}`,
                `DTSTAMP:${nowStr}`,
                `DTSTART;VALUE=DATE:${start}`,
                `DTEND;VALUE=DATE:${end}`,
                `SUMMARY:Workout: ${label}`,
                `DESCRIPTION:Generated by Phalanx Workout Split Builder`,
                `END:VEVENT`
            )

        });
    }
    lines.push('END:VCALENDAR')
    const blob = new Blob([lines.join('\r\n')], { type: 'text/calendar;charset=utf-8' })
    const link = document.createElement('a')
    link.href = URL.createObjectURL(blob)
    link.download = 'workout-split.ics'
    link.click()
    URL.revokeObjectURL(link.href)
}



